name: 'Run tfsec with sarif upload'
description: 'Run tfsec against terraform code base and upload the sarif output to the github repo'
author: 'JaSilez'

inputs:
  working_directory:
    description: |
      Directory to run the action on, from the repo root.
      Default is . ( root of the repository)
    default: '.'
  sarif_file:
    description: The path to write the sarif report, defaults to tfsec.sarif
  tfvars_file:
    description: The tfvars file to use for the scan
  tfsec_version:
    description: The version of tfsec to use for the scan, defaults to latest
    default: latest
outputs:
  tfsec-return-code:
    description: 'tfsec command return code'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/tfsec.sh
      shell: bash
